"""Initial Migration

Revision ID: cd3010438df0
Revises: ca91e868a644
Create Date: 2017-11-05 00:33:56.297052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd3010438df0'
down_revision = 'ca91e868a644'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('feedback_section_id', sa.String(length=255), nullable=True))
    op.drop_column('feedback', 'comment_section_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('comment_section_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('feedback', 'feedback_section_id')
    # ### end Alembic commands ###
